
import React, { useState, useEffect } from 'react';
import { summarizeNews } from '../services/geminiService';

const mockHeadlines = [
    "Reliance Industries (RIL) Q2 results beat estimates, net profit jumps 15%.",
    "IT sector faces headwinds as major US clients cut spending; INFY and TCS trade lower.",
    "HDFC Bank reports strong loan growth, asset quality remains stable.",
    "SEBI introduces new margin rules for derivatives trading, impacting retail traders.",
    "Auto sales figures for October show a mixed trend; Maruti Suzuki up, Tata Motors down.",
    "Pharmaceutical sector gains on back of strong export data and new drug approvals.",
    "Indian stock market indices Sensex and Nifty hit record highs amid positive global cues."
];

const AINewsScreen: React.FC = () => {
    const [summary, setSummary] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(true);

    useEffect(() => {
        const generateSummary = async () => {
            setIsLoading(true);
            const result = await summarizeNews(mockHeadlines);
            setSummary(result);
            setIsLoading(false);
        };
        generateSummary();
    }, []);

    return (
        <main className="animate-fade-in p-6">
            <div className="space-y-6">
                <h2 className="text-3xl font-bold text-text-primary flex items-center">
                    <i className="fas fa-robot text-primary mr-3"></i> AI Market News Analysis
                </h2>
                <p className="text-muted">
                    Get a quick, AI-powered summary of today's key market headlines, generated by Google Gemini.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* AI Summary */}
                    <div className="bg-surface rounded-lg shadow-lg p-6">
                        <h3 className="text-xl font-semibold mb-4">Gemini's Market Pulse</h3>
                        {isLoading ? (
                            <div className="space-y-4 animate-pulse">
                                <div className="h-4 bg-overlay rounded w-3/4"></div>
                                <div className="h-4 bg-overlay rounded w-full"></div>
                                <div className="h-4 bg-overlay rounded w-5/6"></div>
                                <div className="h-4 bg-overlay rounded w-1/2"></div>
                            </div>
                        ) : (
                            <p className="text-text-secondary whitespace-pre-line leading-relaxed">{summary}</p>
                        )}
                    </div>

                    {/* Headlines */}
                    <div className="bg-surface rounded-lg shadow-lg p-6">
                        <h3 className="text-xl font-semibold mb-4">Today's Headlines</h3>
                        <ul className="space-y-3">
                            {mockHeadlines.map((headline, index) => (
                                <li key={index} className="flex items-start">
                                    <i className="fas fa-newspaper text-muted mt-1 mr-3"></i>
                                    <span className="text-text-secondary">{headline}</span>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </div>
        </main>
    );
};

export default AINewsScreen;